name: unittest

on: push

jobs:
  unittest:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: coding-practice
        python-version: 3.7
        auto-activate-base: false
    - name: Setup
      shell: bash -l {0}
      run: make setup
    - name: Test solutions
      shell: bash -l {0}
      run: make test-solutions